<a href="https://colab.research.google.com/github/Muntasir2179/Testing-ML-models-for-Emotion-classification/blob/main/Testing_models_for_Emotion_Detection_from_text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Emotion Detection
* English Text



## Importing libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Importing Dataset

In [ ]:
dataset = pd.read_csv('Emotion Dataset (English Text).csv')

In [ ]:
dataset.head()

serial                                               text    label
0       0                            i didnt feel humiliated  sadness
1       1  i can go from feeling so hopeless to so damned...  sadness
2       2   im grabbing a minute to post i feel greedy wrong    anger
3       3  i am ever feeling nostalgic about the fireplac...     love
4       4                               i am feeling grouchy    anger

## Data cleaning

In [ ]:
!pip install neattext

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import neattext.functions as nfx

In [ ]:
dataset['clean_Text'] = dataset['text'].apply(nfx.remove_stopwords)

In [ ]:
dataset['clean_Text'] = dataset['clean_Text'].apply(nfx.remove_userhandles)

In [ ]:
dataset['clean_Text'] = dataset['clean_Text'].apply(nfx.remove_punctuations)

In [ ]:
dataset['clean_Text'] = dataset['clean_Text'].apply(nfx.remove_special_characters)

In [ ]:
dataset['clean_Text'] = dataset['clean_Text'].str.lower()

In [ ]:
dataset.head()

serial                                               text    label  \
0       0                            i didnt feel humiliated  sadness   
1       1  i can go from feeling so hopeless to so damned...  sadness   
2       2   im grabbing a minute to post i feel greedy wrong    anger   
3       3  i am ever feeling nostalgic about the fireplac...     love   
4       4                               i am feeling grouchy    anger   

                                    clean_Text  
0                        didnt feel humiliated  
1  feeling hopeless damned hopeful cares awake  
2    im grabbing minute post feel greedy wrong  
3    feeling nostalgic fireplace know property  
4                              feeling grouchy

### Stemming and Lemmatizing the clean_text

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
from nltk.stem import PorterStemmer, LancasterStemmer, RegexpStemmer, WordNetLemmatizer
from nltk.tokenize import sent_tokenize, word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


**Choices for pos parameter in the lemmatizer**

*   'n' --> nouns (NN, NNS, NNP, NNPS)
*   'v' --> verbs (VB, VBD, VBG, VBN, VBP, VBZ)
*   'a' --> adjectives (JJ, JJR, JJS)
*   'r' --> adverbs (RB, RBR, RBS)

In [ ]:
# finds nltk tag for each word in a sentence
def lemmatizer_tag_finder(sentence):
  tokens = word_tokenize(sentence)
  tag_list = dict(nltk.pos_tag(tokens))

  for tag in tag_list:
    if tag_list[tag].startswith('NN'):
      tag_list[tag] = 'n'
    elif tag_list[tag].startswith('VB'):
      tag_list[tag] = 'v'
    elif tag_list[tag].startswith('JJ'):
      tag_list[tag] = 'a'
    elif tag_list[tag].startswith('RB'):
      tag_list[tag] = 'r'
    else:
      tag_list[tag] = 'others'

  return tag_list

In [ ]:
# returns a lemmatized sentence
def sentence_lemmatizer(sentence):
  words_and_tags = lemmatizer_tag_finder(sentence)
  lemmatized_sentence = []
  lemmatizer = WordNetLemmatizer()

  for word in words_and_tags:
    if words_and_tags[word] == 'others':
      lemmatized_sentence.append(word)
    else:
      lemmatized_sentence.append(lemmatizer.lemmatize(word, pos=words_and_tags[word]))

  return " ".join(lemmatized_sentence)

In [ ]:
# porter = PorterStemmer()
# reg_stemmer = RegexpStemmer('ing$|s$|e$|able$', min=4)

In [ ]:
# def stemSentence(sentence):
#   token_words = word_tokenize(sentence)
#   stem_sentence = []

#   for word in token_words:
#     stem_sentence.append(reg_stemmer.stem(word))
#     stem_sentence.append(' ')
#   return ''.join(stem_sentence)

In [ ]:
pd.options.mode.chained_assignment = None

length = len(dataset['clean_Text'])

for index in range(0, length):
  sentence = dataset['clean_Text'][index]
  dataset['clean_Text'][index] = sentence_lemmatizer(sentence)

In [ ]:
dataset.head()

serial                                               text    label  \
0       0                            i didnt feel humiliated  sadness   
1       1  i can go from feeling so hopeless to so damned...  sadness   
2       2   im grabbing a minute to post i feel greedy wrong    anger   
3       3  i am ever feeling nostalgic about the fireplac...     love   
4       4                               i am feeling grouchy    anger   

                               clean_Text  
0                    didnt feel humiliate  
1   feel hopeless damn hopeful care awake  
2   im grab minute post feel greedy wrong  
3  feel nostalgic fireplace know property  
4                            feel grouchy

## Data cleaning (Stemming)

In [ ]:
# import re
# import nltk
# nltk.download('stopwords')
# from nltk.corpus import stopwords
# from nltk.stem.porter import PorterStemmer

# corpus = []

# length = len(dataset['text'])

# for i in range(0, length):
#   text = re.sub('[^a-zA-Z]', ' ', dataset['text'][i])
#   text = text.lower()
#   text = text.split()
#   ps = PorterStemmer()
#   all_stopwords = stopwords.words('english')
#   all_stopwords.remove('not')
#   text = [ps.stem(word) for word in text if not word in set(all_stopwords)]
#   text = ' '.join(text)
#   corpus.append(text)

## Creating Bag of Words model

In [ ]:
# from sklearn.feature_extraction.text import CountVectorizer
# cv = CountVectorizer(max_features=11500)
# xfeatures = cv.fit_transform(corpus).toarray()
# ylabels = dataset['label']

## Feature extraction

In [ ]:
xfeatures = dataset['clean_Text']
ylabels = dataset['label']

In [ ]:
xfeatures.head()

0                      didnt feel humiliate
1     feel hopeless damn hopeful care awake
2     im grab minute post feel greedy wrong
3    feel nostalgic fireplace know property
4                              feel grouchy
Name: clean_Text, dtype: object

In [ ]:
ylabels.head()

0    sadness
1    sadness
2      anger
3       love
4      anger
Name: label, dtype: object

### Converting text into vectors

In [ ]:
# vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer()
xfeatures = vectorizer.fit_transform(xfeatures)

In [ ]:
print(xfeatures.todense())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### Spliting data into training set and test set

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(xfeatures, ylabels, test_size=0.2, random_state = 0)

## Building models

In [ ]:
# machine learning models
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

# Metrics
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

In [ ]:
from pandas.core.generic import RandomState
models = {
    'Logistic Regression': LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000),
    'Naive Bayes': MultinomialNB(),
    'Dicision Tree': DecisionTreeClassifier(),
    'SVM': SVC(kernel='rbf', random_state=0),
    'Random Forest': RandomForestClassifier(),
    'KNN': KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
}

for model_index in models:
  # training each model on training set
  model = models[model_index]
  model.fit(x_train, y_train)

  # make prediction
  y_pred = model.predict(x_test)

  # training set performance
  print('Accuracy of the {} model is: {}'.format(model_index, accuracy_score(y_test, y_pred)))

Accuracy of the Logistic Regression model is: 0.866
Accuracy of the Naive Bayes model is: 0.6815
Accuracy of the Dicision Tree model is: 0.82275
Accuracy of the SVM model is: 0.8355
Accuracy of the Random Forest model is: 0.85625
Accuracy of the KNN model is: 0.82325


In [ ]:
# def single_prediction(text, model):
#   text = pd.DataFrame(text)
#   text = text.apply(nfx.remove_stopwords)
#   text = text.apply(nfx.remove_userhandles)
#   text = text.apply(nfx.remove_punctuations)
#   text = text.apply(nfx.remove_special_characters)
#   text = text.str.lower()

#   text = sentence_lemmatizer(text)

#   text = vectorizer.transform(text)

#   print(model.predict(text))